name = "Marthia Seasons: S3"
author = "LittlePengwy, Omega_Exists, MisterFP"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcaba6b0ff9c588014f5f819b367179bb378a15b9ef023f362e5fefecb9cf87c"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
