name = "Marthia Seasons S3"
author = "LittlePengwy, Omega_Exists, MisterFP"
version = "1.0.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fed669c2528def32e8ff2b0218557512d577ebc6174d0717548a74ace44f7eb1"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
