[flavor_groups.clientside]
name = "General Clientside Mods"
description = "Wether you would like to install any purely clientside mods, with a few exceptions, namely Xaeros and Ears."
side = "client"
[[flavor_groups.clientside.choices]]
id = "no_clientside_mods"
name = "None"
description = "Bare minimum, barring a few mods."
[[flavor_groups.clientside.choices]]
id = "some_clientside_mods"
name = "Most"
description = "Most clientside mods, barring a few."

[metafile.3dskinlayers]
flavors = ["no_clientside__mods"]
[metafile.ambient-environment]
flavors = ["no_clientside__mods"]
[metafile.ambientsounds]
flavors = ["no_clientside__mods"]
[metafile.caelum]
flavors = ["no_clientside__mods"]
[metafile.chat-heads]
flavors = ["no_clientside__mods"]
[metafile.continuity]
flavors = ["no_clientside__mods"]
[metafile.connector]
flavors = ["no_clientside__mods"]
[metafile.forgified-fabric-api]
flavors = ["no_clientside__mods"]
[metafile.athena-ctm]
flavors = ["no_clientside__mods"]
[metafile.fusion-connected-textures]
flavors = ["no_clientside__mods"]
[metafile.not-enough-animations]
flavors = ["no_clientside__mods"]
[metafile.oculus]
flavors = ["no_clientside__mods"]
[metafile.shulkerboxtooltip]
flavors = ["no_clientside__mods"]
[metafile.sound-physics-remastered]
flavors = ["no_clientside__mods"]
[metafile.wthit]
flavors = ["no_clientside__mods"]
[metafile.zume]
flavors = ["no_clientside__mods"]

[metafile.distanthorizons]
flavors = ["distant_on"]

[metafile.first-person-model]
flavours = ["model_on"]
