[flavor_groups.clientside]
name = "General Clientside Mods"
description = "Wether you would like to install any purely clientside mods, with a few exceptions, namely Xaeros and Ears."
side = "client"
[[flavor_groups.clientside.choices]]
id = "most_clientside_mods"
name = "Most"
description = "Most clientside mods, barring a few."
[[flavor_groups.clientside.choices]]
id = "no_clientside_mods"
name = "None"
description = "Bare minimum, barring a few mods."

[flavor_groups.dh]
name = "Distant Horizons"
description = "Wether you would like to install Distant Horizons."
side = "client"
[[flavor_groups.dh.choices]]
id = "distanthorizons_on"
name = "On"
description = "Distant Horizons On"
[[flavor_groups.dh.choices]]
id = "distanthorizons_off"
name = "Off"
description = "Distant Horizons Off"

[flavor_groups.model]
name = "First Person Viewmodel"
description = "Wether you would like to install First Person Viewmodel"
side = "client"
[[flavor_groups.model.choices]]
id = "first-person-model_on"
name = "On"
description = "Viewmodel On"
[[flavor_groups.model.choices]]
id = "first-person-model_off"
name = "Off"
description = "Viewmodel Off"

[flavor_groups.invsort]
name = "Inventory Sorter"
description = "Wether you would like to install Inventory Sorter"
side = "client"
[[flavor_groups.invsort.choices]]
id = "inventory-sort_on"
name = "On"
description = "Inventory Sort On"
[[flavor_groups.invsort.choices]]
id = "inventory-sort_off"
name = "Off"
description = "Inventory Sort Off"

[metafile.3dskinlayers]
flavors = "most_clientside_mods"
[metafile.ambient-environment]
flavors = "most_clientside_mods"
[metafile.ambientsounds]
flavors = "most_clientside_mods"
[metafile.appleskin]
flavors = "most_clientside_mods"
[metafile.caelum]
flavors = "most_clientside_mods"
[metafile.chat-heads]
flavors = "most_clientside_mods"
[metafile.continuity]
flavors = "most_clientside_mods"
[metafile.connector]
flavors = "most_clientside_mods"
[metafile.athena-ctm]
flavors = "most_clientside_mods"
[metafile.not-enough-animations]
flavors = "most_clientside_mods"
[metafile.oculus]
flavors = "most_clientside_mods"
[metafile.particle-rain]
flavors = "most_clientside_mods"
[metafile.shulkerboxtooltip]
flavors = "most_clientside_mods"
[metafile.sound-physics-remastered]
flavors = "most_clientside_mods"
[metafile.wthit]
flavors = "most_clientside_mods"
[metafile.zume]
flavors = "most_clientside_mods"

[metafile.distanthorizons]
flavors = "distanthorizons_on"

[metafile.first-person-model]
flavors = "first-person-model_on"

[metafile.inventory-sorter]
flavors = "inventory-sort_on"












